
Lmod is automatically replacing "cce/15.0.0" with "gcc/11.2.0".


Due to MODULEPATH changes, the following have been reloaded:
  1) cray-mpich/8.1.23

/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/ase/utils/__init__.py:62: FutureWarning: Please use atoms.cell.reciprocal()
  warnings.warn(warning)
Traceback (most recent call last):
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/bin/vibes", line 8, in <module>
    sys.exit(cli())
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/vibes/cli/run.py", line 106, in relaxation
    ctx.run(timeout=timeout)
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/vibes/relaxation/context.py", line 158, in run
    run_relaxation(self)
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/vibes/relaxation/workflow.py", line 25, in run_relaxation
    converged = run(ctx)
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/vibes/relaxation/workflow.py", line 74, in run
    metadata2file(ctx.metadata, trajectory_file)
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/vibes/trajectory/io.py", line 67, in metadata2file
    son.dump({**metadata, "vibes": {"version": version}}, file, is_metadata=True)
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/vibes/son.py", line 11, in dump
    return son.dump(*args, **{"dumper": dict2json, **kwargs})
  File "/mnt/lustre/a2fs-work2/work/e05/e05/prakaya/fhi-vibes/lib/python3.9/site-packages/son/interface.py", line 29, in dump
    raise FileExistsError(msg)
FileExistsError: /mnt/lustre/a2fs-work2/work/e05/e05/prakaya/chalcogenide_perovskites/redo/ternary/Ba11Zr10S31_I4_mmm_light/relaxation/trajectory.son exists, possibility of data loss!
